// Where it gets documented. Every run writes one JSON evidence file, and
// CONTROL-STATUS.md is regenerated as the human-readable dashboard.
// In Actions these are committed to git, so history is append-only and attributable.
// (A real program would also ship them to WORM storage, e.g. S3 Object Lock.)
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { ROOT } from "./config.mjs";

// Stores the record and its own repo-relative path (record.evidence_file).
export function writeEvidence(record, kind = "run") {
  const iso = new Date(record.started_at).toISOString();
  const rel = `evidence/runs/${iso.slice(0, 10)}/${iso.slice(11, 19).replaceAll(":", "")}Z-${kind}.json`;
  record.evidence_file = rel;
  mkdirSync(join(ROOT, rel, ".."), { recursive: true });
  writeFileSync(join(ROOT, rel), JSON.stringify(record, null, 2) + "\n");
  return rel;
}

const icon = (r) => (r === undefined ? "–" : r.pass ? "✅" : "❌");

export function writeStatus(record, control) {
  const ids = [...Object.keys(control.assertions.preventive), ...Object.keys(control.assertions.detective).filter((k) => k.startsWith("D"))];
  const lines = [
    `# ${control.id} control status`,
    "",
    `> ${control.statement.trim()}`,
    "",
    `Last run: **${record.started_at}** (trigger: ${record.trigger}) · Evidence: \`${record.evidence_file}\``,
    "",
    `| Repo | Scope | Result | ${ids.join(" | ")} |`,
    `|---|---|---|${ids.map(() => ":-:").join("|")}|`,
  ];
  for (const r of record.repos) {
    const final = r.after_remediation ?? r.evaluation;
    const result = !final ? "not tested" : final.status === "PASS" ? "PASS" : r.after_remediation ? "STILL FAILING" : "FAIL";
    const fixed = r.after_remediation && r.evaluation.status === "FAIL" ? " (auto-fixed)" : "";
    const cells = ids.map((id) => icon(final?.results[id] ?? r.evaluation?.results[id]));
    lines.push(`| ${r.repo} | ${r.scope.status}${r.scope.unclassified ? " (unclassified)" : ""} | ${result}${fixed} | ${cells.join(" | ")} |`);
  }
  if (record.agent?.summary) lines.push("", "## Agent summary", "", record.agent.summary);
  lines.push("", "_Generated by `src/run.mjs`. Do not edit by hand._", "");
  writeFileSync(join(ROOT, "CONTROL-STATUS.md"), lines.join("\n"));
}
